service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  run:
    handler: run.handler
    events:
      - http:
          method: ANY
          path: /{any+}
          